name: Linux Container Node Workflow

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: acrcontainerdemox.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build dotnetapp -t acrcontainerdemox.azurecr.io/dotnetapp:${{ github.sha }}
        docker push acrcontainerdemox.azurecr.io/dotnetapp:${{ github.sha }}

    - uses: azure/appservice-settings@v1
      with:
        app-name: 'app-container-demo-db'
        app-settings-json: '[{"name": "WEBSITES_PORT", "value": "1433"}, {"name": "SA_PASSWORD", "value": "Your_password123"), {"name": "ACCEPT_EULA", "value": "Y"}]'

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-container-demo-db'
        images: 'mcr.microsoft.com/mssql/server'

    - uses: azure/appservice-settings@v1
      with:
        app-name: 'app-container-demo'
        app-settings-json: '[{"name": "ASPNETCORE_ENVIRONMENT", "value": "Production"}]'

    # az webapp config appsettings set --resource-group <group-name> --name <app-name> --settings DB_HOST="myownserver.mysql.database.azure.com"

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-container-demo'
        images: 'acrcontainerdemox.azurecr.io/dotnetapp:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout